index:
   path: /
   controller: App\Controller\DefaultController::index
aura:
   path: /aura_mobile_user
   controller: App\Controller\DefaultController::aura
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
# app_lucky_number:
#     path: /lucky
#     controller: App\Controller\LuckyController::number
